sapphiredev/shapeshift

README.md, src/constraints/NumberConstraints.ts, src/validators/BaseValidator.ts, src/validators/NumberValidator.ts, tests/validators/number.test.ts
Adds the following methods:
- `BaseValidator#transform`
- `s.number.divisibleBy(n)`
- `s.number.abs`
- `s.number.sign`
- `s.number.trunc`
- `s.number.floor`
- `s.number.fround`
- `s.number.round`
- `s.number.ceil`
=> feat: added number transformers

README.md, src/lib/Shapes.ts, src/type-exports.ts, src/validators/ArrayValidator.ts, tests/validators/array.test.ts
I used `as any` casts to silence the compiler complaining about `T` types not matching.
Also tried to avoid overload hell... by making use of TypeScript 4.1+ features.
=> feat(Array): generate tuple types with given length

src/validators/UnionValidator.ts, tests/validators/union.test.ts
The overridden methods were not supposed to nest UnionValidators
=> fix(s.union): fix union overrides

README.md, src/validators/ObjectValidator.ts, tests/validators/object.test.ts
One last thing Zod has that Shapeshift didn't yet, [`s.object.passthrough`](https://www.npmjs.com/package/zod#passthrough).
=> feat(s.object): add passthrough

.vscode/settings.json, jest.config.mjs, tests/common/macros/comparators.ts, tests/jest.setup.ts, tests/validators/string.test.ts
=> test: increase test coverage for email validation

src/validators/ObjectValidator.ts, tests/validators/object.test.ts
Note: this is a hella breaking change: Possibly undefined keys will now actually be missing from the object!
=> perf: speed up object validation a LOT

src/validators/BaseValidator.ts
Given the following code:
```ts
/**
* Removes `null`, `undefined` and `?` from an object
* This essentially combines `Required<T>`,
* `NonNullable<T>` and `NonUndefined<T>`
*/
type NonNullish<T> = {
[P in keyof T]-?: Exclude<T[P], undefined | null>;
};
/**
* Type union for the full 2 billion dollar mistake in the JavaScript ecosystem
*/
type Nullish = null | undefined;
interface MyArgs {
offset: number | Nullish;
take: number | Nullish;
}
/**
* Validate the schema
*
* Note: After calling `parse` the values will never be
* `null` or `undefined` because of the nullish coalescing.
*/
const schema: SchemaOf<MyArgs> = s.object({
offset: s.number.greaterThanOrEqual(0).nullish.transform((v) => v ?? 0),
take: s.number
.greaterThanOrEqual(1)
.lessThanOrEqual(50)
.nullish.transform((v) => v ?? 1), …
```
=> fix: add generic type to parse

src/lib/util-types.ts, src/validators/ObjectValidator.ts
This pr makes keys optional instead of `| undefined`.
This is a hacky solution, I've tried various ways for 1 hr but can't find a better way of doing it, so if anyone has a better solution then lmk.
[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgdmArsKBeKBvAUASwCYBcUAzsAE45wDmA3FosRGXAIYC2ERpF1UAPlERw8EAGaUIeOgF8sWUJCgAFHAGMA1gBExEvAB4AKgD40WKOcxQA2gGkolKOoggA9qKgGoLYoOE64klAQAB7AEMI+BrYAulAA-FABAG5MUER20URRNrGycgrQKhoAqn7iAXgAsixOAPJgwDgurAA2hiaoZhYY1nYOTq7unt6+IuWBIWERHjHmCXZEyanRcUQAosGqLYgihjEANKP+kiZ58uDQpWO6Bi71jc0sbcZoympax-ovAGRvJWW6ap1BpNVrtKByERbFhkaCqZqkKDBAhXT63e6gp56eBIYBGOTBAB0+C6AHpSQA9OJYIkMJisDhkynUoA)
=> fix: make keys optional in object parsing

src/lib/Shapes.ts, src/validators/LazyValidator.ts, tests/validators/lazy.test.ts
ref: https://github.com/jquense/yup#lazyvalue-any--schema-lazy
=> feat: lazy validator

src/lib/Shapes.ts
After this change the following 3 will all resolve their types properly:
=> fix: fixed `s.array` type inference

package.json, src/tsconfig.json, tests/tsconfig.json, tsup.config.ts
Seeing as our tests do not need composite builds we can disable that in src and then enable `dts` in tsup to make the build process quicker and easier
=> build: use tsup `dts` option

src/constraints/util/isUnique.ts
=> fix: fast deep equal import

package.json, yarn.lock
@favware/rollup-type-bundler is no longer necessary
=> chore: cleaup unnecessary deps

package.json, tsup.config.ts, yarn.lock
esbuild tree-shake doesn't removes duplicate imports. So enabled rollup tree-shake
~~blocked by: https://github.com/egoist/tsup/pull/692~~ merged and released
=> build: enable rollup tree-shaking

src/lib/util-types.ts
I broke jump to definition of `ObjectValidator` when adding `undefinedToOptional`
ref: https://github.com/microsoft/TypeScript/issues/47813
there's a pr to fix it too: https://github.com/microsoft/TypeScript/pull/51650
=> fix: fixed "jump to definition" for `undefinedToOptional` going to wrong symbol

src/lib/Shapes.ts, src/lib/util-types.ts, src/validators/ObjectValidator.ts
ref: https://github.com/discordjs/discord.js/pull/8868#discussion_r1032867137
=> refactor: remove `NonNullObject`

.prettierignore, .prettierrc.js, README.md, package.json, src/constraints/ObjectConstrains.ts, src/constraints/base/IConstraint.ts, src/constraints/type-exports.ts, src/constraints/util/isUnique.ts, src/lib/errors/BaseConstraintError.ts, src/validators/BaseValidator.ts, src/validators/ObjectValidator.ts, tests/validators/object.test.ts, yarn.lock
~~_Not ready for review yet. I haven't even started. Just fixed the typings and added a test_~~
~~I'll finish it after my exams. In the meantime, if anyone else is interested then u can create a pr and I'll close this one~~
The code is ready for review.
TODO:
=> feat: add `when` constraint

src/lib/errors/BaseError.ts, src/lib/errors/CombinedError.ts, src/lib/errors/CombinedPropertyError.ts, src/lib/errors/ExpectedConstraintError.ts, src/lib/errors/ExpectedValidationError.ts, src/lib/errors/MissingPropertyError.ts, src/lib/errors/MultiplePossibilitiesConstraintError.ts, src/lib/errors/UnknownEnumValueError.ts, src/lib/errors/UnknownPropertyError.ts, src/lib/errors/ValidationError.ts
=> fix: remove `node:` prefix

src/constraints/StringConstraints.ts, tests/validators/string.test.ts
Even though the U in URL is a vowel, the U is pronounced “you.”. Since the letter Y is a consonant in this case, "a" needs to be used here instead of "an".
=> fix: resolve minor grammar mistake

src/validators/BaseValidator.ts, tests/validators/base.test.ts
ref: https://canary.discord.com/channels/737141877803057244/934614121687687179/1103324956579856414
=> feat: add BaseValidator.describe

package.json
I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
⚠️ this PR focuses solely on fixing "🐛 Used fallback condition" problem but the "🎭 Masquerading as CJS" remains here. You can check the reported errors …
=> fix(types): move the `types` condition to the front
