sapphiredev/shapeshift

README.md
src/constraints/BigIntConstraints.ts
src/constraints/BooleanConstraints.ts
src/constraints/DateConstraints.ts
src/constraints/NumberConstraints.ts
src/constraints/base/IConstraint.ts
src/constraints/util/operators.ts
src/lib/Shapes.ts
src/lib/errors/ConstraintError.ts
src/validators/BaseValidator.ts
src/validators/BigIntValidator.ts
src/validators/BooleanValidator.ts
src/validators/DateValidator.ts
src/validators/NeverValidator.ts

Added `s.bigint`
Added `s.boolean`
Added `s.date`
Added `s.literal(Date)`
Added `s.never`

feat: added more primitives

---

README.md
src/lib/Shapes.ts
tests/validators/union.test.ts

I've tried to fix union type but if this isn't the best way of doing this then lmk how I can do it.

fix: fix union type and add test

---

tests/validators/boolean.test.ts
tests/validators/date.test.ts
tests/validators/instance.test.ts
tests/validators/never.test.ts
tests/validators/nullish.test.ts
tests/validators/set.test.ts

add new tests

---

package.json

feat: allow the use of module: NodeNext

---

src/constraints/ArrayLengthConstraints.ts
src/constraints/BigIntConstraints.ts
src/constraints/BooleanConstraints.ts
src/constraints/DateConstraints.ts
src/constraints/NumberConstraints.ts
src/constraints/StringConstraints.ts
src/constraints/base/IConstraint.ts
src/constraints/util/common/combinedResultFn.ts
src/constraints/util/urlValidators.ts
src/index.ts
src/lib/errors/BaseConstraintError.ts
src/lib/errors/ExpectedConstraintError.ts
src/lib/errors/MultiplePossibilitiesConstraintError.ts
src/type-exports.ts
tests/common/macros/comparators.ts
tests/lib/errors/ExpectedConstraintError.test.ts
tests/lib/errors/MultiplePossibilitiesConstraintError.test.ts
tests/validators/array.test.ts
tests/validators/bigint.test.ts
tests/validators/boolean.test.ts
tests/validators/date.test.ts
tests/validators/number.test.ts
tests/validators/string.test.ts

Resolving a TODO and then improving IP's error reporting performance

perf(s.string): speed up URL and IP constraints

---

src/constraints/util/emailValidator.ts

Speeds up the email validator from 0.25 times in the worst cases to up to 10 times faster, by removing nearly all memory allocations.
Documented is heavily more documented to explain the far more advanced code in detail.

refactor(email-validator): rewrite for huge performance boosts

---

src/constraints/DateConstraints.ts
src/validators/DateValidator.ts
tests/validators/base.test.ts
tests/validators/date.test.ts
tests/validators/union.test.ts

Also added some missing constraints from s.date

tests: increase coverage

---

tests/util/common/combinedResultFn.test.ts

tests: add coverage for `combinedErrorFn`

---

README.md

docs(readme): add todo notice for `reshape` and `function` validations

---

src/validators/NativeEnumValidator.ts

chore: optimize NativeEnum

---

package.json
src/index.ts
src/type-exports.ts
yarn.lock

fix: ensure `BaseError` is exported as value

---

src/index.ts
src/utility-types.ts

These 2 are just plain useful to have for type safety

feat: add 2 utility types inspired by yup and co

---

src/validators/ObjectValidator.ts
tests/validators/object.test.ts

fix(ObjectValidator): fix #121

---

README.md
src/validators/ObjectValidator.ts
src/validators/UnionValidator.ts
tests/validators/object.test.ts
tests/validators/union.test.ts

This pr adds `required` gatter to `ObjectValidator` also fixed typings for `strict`

feat: add `required` in object validation

---

src/validators/ObjectValidator.ts

sorry, I forgot to add the return type

build: fix strict return type

---

src/constraints/StringConstraints.ts
src/constraints/util/net.ts

This way shapeshift is 1 step closer to being browser bundle ready

refactor: port net module

---

src/validators/BaseValidator.ts
tests/validators/base.test.ts

feat: add `Validator#is`

---

src/constraints/StringConstraints.ts
src/constraints/util/phoneValidator.ts
src/validators/StringValidator.ts
tests/validators/string.test.ts

feat: add `s.string.phone` 

---

src/constraints/ObjectConstrains.ts
src/constraints/util/isUnique.ts

lodash doesn't uses `exports` so 😞

fix: fixed lodash esm import

---

src/validators/UnionValidator.ts
tests/lib/errors/BaseConstraintError.test.ts
tests/lib/errors/BaseError.test.ts
tests/validators/array.test.ts
tests/validators/base.test.ts
tests/validators/bigint.test.ts
tests/validators/boolean.test.ts
tests/validators/date.test.ts
tests/validators/enum.test.ts
tests/validators/instance.test.ts
tests/validators/lazy.test.ts
tests/validators/literal.test.ts
tests/validators/map.test.ts
tests/validators/nativeEnum.test.ts
tests/validators/never.test.ts
tests/validators/null.test.ts
tests/validators/nullish.test.ts
tests/validators/number.test.ts
tests/validators/object.test.ts
tests/validators/passthrough.test.ts
tests/validators/record.test.ts
tests/validators/set.test.ts
tests/validators/tuple.test.ts
tests/validators/typedArray.test.ts
tests/validators/undefined.test.ts
tests/validators/union.test.ts
vitest.config.ts

* Add new custom message tests for all shapes

test: add message cases for all tests
